//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalBusinessCard.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitalBusinessCard.Language.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string activ {
            get {
                return ResourceManager.GetString("activ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Contacts.
        /// </summary>
        public static string addcontact {
            get {
                return ResourceManager.GetString("addcontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin.
        /// </summary>
        public static string bitcoin {
            get {
                return ResourceManager.GetString("bitcoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitcoin Wallet.
        /// </summary>
        public static string btcwal {
            get {
                return ResourceManager.GetString("btcwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendly.
        /// </summary>
        public static string calendly {
            get {
                return ResourceManager.GetString("calendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Info.
        /// </summary>
        public static string cardinfo {
            get {
                return ResourceManager.GetString("cardinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Information.
        /// </summary>
        public static string cardinfor {
            get {
                return ResourceManager.GetString("cardinfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashapp.
        /// </summary>
        public static string cashapp {
            get {
                return ResourceManager.GetString("cashapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Password For Your Later Logins.
        /// </summary>
        public static string chose {
            get {
                return ResourceManager.GetString("chose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CKB Banka.
        /// </summary>
        public static string ckb {
            get {
                return ResourceManager.GetString("ckb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string comm {
            get {
                return ResourceManager.GetString("comm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Website.
        /// </summary>
        public static string compweb {
            get {
                return ResourceManager.GetString("compweb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Card.
        /// </summary>
        public static string copycard {
            get {
                return ResourceManager.GetString("copycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        public static string copytoclipboard {
            get {
                return ResourceManager.GetString("copytoclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Wallet.
        /// </summary>
        public static string crypto {
            get {
                return ResourceManager.GetString("crypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string discord {
            get {
                return ResourceManager.GetString("discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string editt {
            get {
                return ResourceManager.GetString("editt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Mail Adress.
        /// </summary>
        public static string emailadress {
            get {
                return ResourceManager.GetString("emailadress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereum.
        /// </summary>
        public static string eth {
            get {
                return ResourceManager.GetString("eth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethereum Wallet.
        /// </summary>
        public static string ethwal {
            get {
                return ResourceManager.GetString("ethwal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string finance {
            get {
                return ResourceManager.GetString("finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Your Card Now.
        /// </summary>
        public static string get {
            get {
                return ResourceManager.GetString("get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string github {
            get {
                return ResourceManager.GetString("github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Home.
        /// </summary>
        public static string gohome {
            get {
                return ResourceManager.GetString("gohome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string iban {
            get {
                return ResourceManager.GetString("iban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lovcen Banka.
        /// </summary>
        public static string lovcen {
            get {
                return ResourceManager.GetString("lovcen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Card.
        /// </summary>
        public static string mycard {
            get {
                return ResourceManager.GetString("mycard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string newuser {
            get {
                return ResourceManager.GetString("newuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal.
        /// </summary>
        public static string paypal {
            get {
                return ResourceManager.GetString("paypal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill Your Basic Visit Card Information.
        /// </summary>
        public static string please {
            get {
                return ResourceManager.GetString("please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR Code.
        /// </summary>
        public static string qrcode {
            get {
                return ResourceManager.GetString("qrcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show On Profile.
        /// </summary>
        public static string showon {
            get {
                return ResourceManager.GetString("showon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string signal {
            get {
                return ResourceManager.GetString("signal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype.
        /// </summary>
        public static string skype {
            get {
                return ResourceManager.GetString("skype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapchat.
        /// </summary>
        public static string snap {
            get {
                return ResourceManager.GetString("snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram.
        /// </summary>
        public static string telegram {
            get {
                return ResourceManager.GetString("telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiktok.
        /// </summary>
        public static string tiktok {
            get {
                return ResourceManager.GetString("tiktok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch.
        /// </summary>
        public static string twitch {
            get {
                return ResourceManager.GetString("twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string usernam {
            get {
                return ResourceManager.GetString("usernam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string userrole {
            get {
                return ResourceManager.GetString("userrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venmo.
        /// </summary>
        public static string venmo {
            get {
                return ResourceManager.GetString("venmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string verified {
            get {
                return ResourceManager.GetString("verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viber.
        /// </summary>
        public static string viber {
            get {
                return ResourceManager.GetString("viber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet No.
        /// </summary>
        public static string walletno {
            get {
                return ResourceManager.GetString("walletno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeChat.
        /// </summary>
        public static string wechat {
            get {
                return ResourceManager.GetString("wechat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp.
        /// </summary>
        public static string whatsapp {
            get {
                return ResourceManager.GetString("whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yelp.
        /// </summary>
        public static string yelp {
            get {
                return ResourceManager.GetString("yelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ziraat Bank.
        /// </summary>
        public static string ziraat {
            get {
                return ResourceManager.GetString("ziraat", resourceCulture);
            }
        }
    }
}
